### PR TITLE
fix(google): sort resolved variants when fetching font css

### LINKED ISSUE #32: "Tuples must be sorted" error with google fonts provider and multiple font weights
I'm encounting an error when using google fonts provider and multiple font weights. Nuxt reports a `400 bad request` error. Looks like Google enforces a sorted tuple for requests.

**Request link**: `https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,100;1,100;0,200;1,200;0,300;1,300;0,400;1,400;0,500;1,500;0,600;1,600;0,700;1,700`

**Error from Google**: 
```
400: Invalid selector
Tuples must be sorted
IBM Plex Mono:ital,wght@0,100;1,100;0,200;1,200;0,300;1,300;0,400;1,400;0,500;1,500;0,600;1,600;0,700;1,700
```

**My config**:
```
fonts: {
  families: [
    { name: 'IBM Plex Mono', provider: 'google' },
  ],
  defaults: {
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    styles: ['normal', 'italic'],
    subsets: [
      'latin-ext',
      'latin',
    ],
  },
  assets: {
    prefix: '/_fonts',
  },
},
```

### PR DESCRIPTION
**Pull request by qwerzl**
Just a very simple fix to sort the variables list for Google Fonts. This fixes #32.

### CODE REVIEW

File: src/providers/google.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ async function getFontDetails (family: string, variants: ResolveFontFacesOptions
     ? [`${variableWeight.min}..${variableWeight.max}`]
     : variants.weights.filter(weight => String(weight) in font.fonts)
   const resolvedVariants = weights.flatMap(w => [...styles].map(s => `${s},${w}`))
```
Comment (danielroe) [inline src/providers/google.ts:79]:
```suggestion
  const resolvedVariants = weights.flatMap(w => [...styles].map(s => `${s},${w}`)).sort()
```

File: src/providers/google.ts [hunk 2]
```diff
@@ -77,7 +77,7 @@ async function getFontDetails (family: string, variants: ResolveFontFacesOptions
...
-
+  resolvedVariants.sort()
```
Comment (danielroe) [inline src/providers/google.ts:80]:
```suggestion

```

File: src/providers/google.ts [hunk 3]
```diff
@@ -76,8 +76,7 @@ async function getFontDetails (family: string, variants: ResolveFontFacesOptions
   const weights = variableWeight
     ? [`${variableWeight.min}..${variableWeight.max}`]
     : variants.weights.filter(weight => String(weight) in font.fonts)
-  const resolvedVariants = weights.flatMap(w => [...styles].map(s => `${s},${w}`))
-
+  const resolvedVariants = weights.flatMap(w => [...styles].map(s => `${s},${w}`)).sort()
```
Comment (danielroe) [inline src/providers/google.ts:79]:
```suggestion
  const resolvedVariants = weights.flatMap(w => [...styles].map(s => `${s},${w}`)).sort()

```

**Review by danielroe — APPROVED** [review]
Thank you! ❤️
