### PR TITLE
fix(adobe): use provided `css_names` from API

### LINKED ISSUE #187: Adobe doesn't load
Hi guys,

This package seems just what my project needs! 

Unfortunately, adobe fonts do no load. 
N.B> Adobe doesn't load in the playground either...

Hope it will be sorted,

kind regards,

Marco

### PR DESCRIPTION
**Pull request by qwerzl**
@danielroe 

This PR resolves #187. I'm not sure whether this `css_names` always have a single value, it's not documented anywhere.

### CODE REVIEW

File: src/providers/adobe.ts [hunk 1]
```diff
@@ -116,10 +116,10 @@ async function getFontDetails(family: string, variants: ResolveFontFacesOptions)
     }
     const css = await fontCSSAPI<string>(`${fonts.kits[kit]!.id}.css`)
 
-    // Adobe uses slugs instead of names in its CSS to define its font faces,
-    // so we need to first transform names into slugs.
-    const slug = family.toLowerCase().split(' ').join('-')
-    return addLocalFallbacks(family, extractFontFaceData(css, slug))
+    // TODO: Not sure whether this css_names array always has a single element. Still need to investigate.
+    const cssName = font.css_names[0]!
```
Comment (danielroe) [inline src/providers/adobe.ts:120]: Maybe fall back to previous 'slug' if it's missing for any reason?

Comment (danielroe) [reply src/providers/adobe.ts:120]:
```suggestion
    const cssName = font.css_names[0] ?? family.toLowerCase().split(' ').join('-')
```

**Comment by qwerzl** [comment]
@danielroe Merged.

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Nice! 👌
