### PR TITLE
 fix: normalize weights before passing to `resolveFontFaces`

### LINKED ISSUE #46: Failure to match font weights for `fontshare` provider when the `weights` defined in the config is composed of strings.
When the weights are defined string arrays in the config, the fontshare provider would fail to match the correct weights because of the type mismatch.

**My config**:
```
export default defineNuxtConfig({
  modules: ['@nuxt/fonts', '@nuxtjs/tailwindcss', '@unocss/nuxt'],
  unocss: {
    disableNuxtInlineStyle: false,
  },
  fonts: {
    providers: {
      custom: '~/providers/custom'
    },
    families: [
      { name: 'Abel', provider: 'bunny' },
      { name: 'Satoshi', provider: 'fontshare' },
      { name: 'Kode Mono', provider: 'none' },
      { name: 'MyCustom', src: '/custom-font.woff2' },
      { name: 'CustomGlobal', global: true, src: '/font-global.woff2' },
      { name: 'Oswald', fallbacks: ['Times New Roman'] },
    ],
    defaults: {
      weights: ['400', '700'],
      fallbacks: {
        monospace: ['Tahoma']
      }
    }
  },
})
```

### PR DESCRIPTION
**Pull request by qwerzl**
This PR fixes #46. Just a simple fix which ensures `variants.weights` is composed of numbers.

### CODE REVIEW

File: src/providers/fontshare.ts [hunk 1]
```diff
@@ -95,6 +95,7 @@ function isFontshareFont (family: string) {
 
 async function getFontDetails (family: string, variants: ResolveFontFacesOptions) {
   // https://api.fontshare.com/v2/css?f[]=alpino@300
+  variants.weights = variants.weights.map(Number)
```
Comment (danielroe) [inline src/providers/fontshare.ts:98]: I think it would be safer to convert to strings in case something like ‘bold’ is provided.

Comment (qwerzl) [reply src/providers/fontshare.ts]: Right. Fixed now.

**Review by danielroe — APPROVED** [review]
Thank you for this and for all your contributions ❤️
